const MODAL_TYPES = {
  DELETE_JOB: "DELETE_JOB",
  JOB_AUTOSCREENING: "JOB_AUTOSCREENING",
};

const TITLES_BY_TYPE = {
  [MODAL_TYPES.DELETE_JOB]: "Delete Job",
  [MODAL_TYPES.JOB_AUTOSCREENING]: "Autoscreening",
};

const MODAL = { MODAL_TYPES, TITLES_BY_TYPE };

export default MODAL;
