const EMPLOYMENT_TYPES = {
  FULL_TIME: "fullTime",
  PART_TIME: "partTime",
  PROJECT: "project",
};

const WORK_NATURE_TYPES = {
  ON_SITE: "onSite",
  REMOTE: "remote",
  HYBRID: "hybrid",
};

const WORK_NATURE_TITLES = {
  [WORK_NATURE_TYPES.ON_SITE]: "On-Site",
  [WORK_NATURE_TYPES.REMOTE]: "Remote",
  [WORK_NATURE_TYPES.HYBRID]: "Hybrid",
};

const ACTION_TYPES = {
  PUBLISH: "PUBLISH",
  EDIT: "EDIT",
};

const STATUS_TYPES = {
  PUBLISHED: "PUBLISHED",
  DRAFT: "DRAFT",
  ARCHIVED: "ARCHIVED",
};

const AUTOSCREENING_QUESTION_TYPES = {
  ONE_RIGHT_ANSWER: "ONE_RIGHT_ANSWER",
  MULTIPLE_RIGHT_ANSWERS: "MULTIPLE_RIGHT_ANSWERS",
  OPEN_QUESTION: "OPEN_QUESTION",
  CODE_CHALLENGE: "CODE_CHALLENGE",
};

const AUTOSCREENING_QUESTIONS_OPTIONS = [
  {
    value: AUTOSCREENING_QUESTION_TYPES.ONE_RIGHT_ANSWER,
    label: "Question with one correct answer",
  },
  {
    value: AUTOSCREENING_QUESTION_TYPES.MULTIPLE_RIGHT_ANSWERS,
    label: "Question with multiple correct answers",
  },
  {
    value: AUTOSCREENING_QUESTION_TYPES.OPEN_QUESTION,
    label: "Open question",
  },
  {
    value: AUTOSCREENING_QUESTION_TYPES.CODE_CHALLENGE,
    label: "Code challenge",
  },
];

const AUTOSCREENING_DEFAULT_QUESTIONS = {
  [AUTOSCREENING_QUESTION_TYPES.ONE_RIGHT_ANSWER]: {
    question: "",
    addButtonTitle: "",
    answers: [],
  },
  [AUTOSCREENING_QUESTION_TYPES.MULTIPLE_RIGHT_ANSWERS]: {},
  [AUTOSCREENING_QUESTION_TYPES.OPEN_QUESTION]: {},
  [AUTOSCREENING_QUESTION_TYPES.CODE_CHALLENGE]: {},
};

const AUTOSCREENING_DEFAULT_ANSWERS = {
  [AUTOSCREENING_QUESTION_TYPES.ONE_RIGHT_ANSWER]: {
    isCorrect: false,
  },
  [AUTOSCREENING_QUESTION_TYPES.MULTIPLE_RIGHT_ANSWERS]: {},
  [AUTOSCREENING_QUESTION_TYPES.OPEN_QUESTION]: {},
  [AUTOSCREENING_QUESTION_TYPES.CODE_CHALLENGE]: {},
};

const AUTOSCREENING_TEXT_CONTENT_BY_TYPE = {
  [AUTOSCREENING_QUESTION_TYPES.ONE_RIGHT_ANSWER]: {
    answersTitle: "Write the options and mark the correct answer.",
    blankMessage: "No options added",
    addButtonLabel: "add option",
  },
};

const POST_JOB = {
  EMPLOYMENT_TYPES,
  WORK_NATURE_TYPES,
  WORK_NATURE_TITLES,
  ACTION_TYPES,
  STATUS_TYPES,
  AUTOSCREENING_QUESTION_TYPES,
  AUTOSCREENING_QUESTIONS_OPTIONS,
  AUTOSCREENING_DEFAULT_QUESTIONS,
  AUTOSCREENING_DEFAULT_ANSWERS,
  AUTOSCREENING_TEXT_CONTENT_BY_TYPE,
};

export default POST_JOB;
